---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
'Twas brillig, and the slithy toves  
Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
And the mome raths outgrabe.  
  
'Beware the Jabberwock, my son!  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Two roads diverged in a yellow wood,    
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,  
 Shining with all his might:  
 He did his very best to make  
 The billows smooth and bright--  
 And this was odd, because it was  
 The middle of the night.  
  
  
 The moon was shining sulkily,  
 Because she thought the sun  
 Had got no business to be there  
 After the day was done--  
 "It's very rude of him," she said,  
 "To come and spoil the fun!" 

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Let me not to the marriage of true minds  
 Admit impediments; love is not love  
 Which alters when it alteration finds,  
 Or bends with the remover to remove:  
 O, no, it is an ever-fixèd mark,  
 That looks on tempests and is never shaken;  
 It is the star to every wand’ring bark,  
 Whose worth’s unknown, although his heighth be taken.  
 Love’s not Time’s fool, though rosy lips and cheeks  
 Within his bending sickle’s compass come;  
 Love alters not with his brief hours and weeks,  
 But bears it out even to the edge of doom.  
 If this be error and upon me proved,  
 I never writ, nor no man ever loved.
